# Copyright (C) 2022 - 2026 Synopsys, Inc. and ANSYS, Inc. All rights reserved.
# SPDX-License-Identifier: MIT
#
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# DO NOT EDIT.
# This file is automatically generated from the RMS OpenApi Specification
# using datamodel-code-generator.

from __future__ import annotations

from datetime import datetime
from typing import Any

from pydantic import AnyUrl, ConfigDict, Field

from ansys.hps.client.common import DictModel


class AnalyticsData(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    number_accessible: int
    number_accessible_assignable_and_matching: int
    number_assignable: int
    number_matching: int


class AnalyzeHpcResources(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    exclusive: bool | None = None
    local_scratch_dir: str | None = None
    native_submit_options: str | None = None
    num_cores_per_node: int | None = None
    num_gpus_per_node: int | None = None
    queue: str | None = None
    use_local_scratch: bool | None = None


class AnalyzePermission(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    permission_type: str
    role: str
    value_id: str
    value_name: str


class AnalyzeRequiredSoftware(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    version: str | None = None


class AnalyzeResourceRequirements(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    compute_resource_set_id: str | None = None
    custom: dict[str, Any] | None = None
    disk_space: int | None = None
    distributed: bool | None = None
    evaluator_id: str | None = None
    hpc_resources: AnalyzeHpcResources | None = None
    memory: int | None = None
    num_cores: float | None = None
    platform: str | None = None


class AnalyzeResponseRequirements(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    accessible: bool | None = None
    assignable: bool | None = None
    has_applications: bool | None = None
    has_custom: bool | None = None
    has_hardware: bool | None = None
    has_platform: bool | None = None


class AnalyzeResponseScaler(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    compute_resource_set_id: str
    requirements: AnalyzeResponseRequirements | None = None
    resource_requirements: AnalyzeResourceRequirements
    scaler_id: str
    software_requirements: list[AnalyzeRequiredSoftware] | None


class ComputeResourceSetsBodyInputBody(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    compute_resource_sets: list[dict[str, Any]] | None


class ConfigUpdatesBodyInputBody(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    configuration_updates: list[dict[str, Any]] | None


class ErrorDetail(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    location: str | None = Field(
        None,
        description="Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'",
    )
    message: str | None = Field(None, description="Error message text")
    value: Any | None = Field(None, description="The value at the given location")


class ErrorModel(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    detail: str | None = Field(
        None,
        description="A human-readable explanation specific to this occurrence of the problem.",
        examples=["Property foo is required but is missing."],
    )
    errors: list[ErrorDetail] | None = Field(
        None, description="Optional list of individual error details"
    )
    instance: AnyUrl | None = Field(
        None,
        description="A URI reference that identifies the specific occurrence of the problem.",
        examples=["https://example.com/error-log/abc123"],
    )
    status: int | None = Field(None, description="HTTP status code", examples=[400])
    title: str | None = Field(
        None,
        description="A short, human-readable summary of the problem type. This value should not change between occurrences of the error.",
        examples=["Bad Request"],
    )
    type: AnyUrl | None = Field(
        "about:blank",
        description="A URI reference to human-readable documentation for the error.",
        examples=["https://example.com/errors/example"],
    )


class EvaluatorRegistration(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    account_id: str | None = Field(None, description="Account ID for multi-tenancy")
    build_info: dict[str, Any] | None = Field(None, description="Build version information")
    change_requested: datetime | None = Field(
        None,
        description="When a configuration change was requested (ISO 8601 timestamp)",
    )
    compute_resource_set_id: str | None = Field(
        None, description="Associated compute resource set ID"
    )
    created_by: str | None = Field(None, description="User who created this evaluator")
    host_id: str | None = Field(None, description="Host identifier where evaluator is running")
    host_name: str | None = Field(None, description="Host name where evaluator is running")
    house_cleaned: bool | None = Field(
        None,
        description="Flag indicating housekeeper has processed abnormal shutdown_status. Default: false",
    )
    id: str | None = Field(None, description="Unique identifier for the evaluator")
    is_admin: bool | None = Field(None, description="Whether this evaluator has admin privileges")
    last_modified: datetime | None = Field(None, description="Last modified timestamp")
    last_modified_by: str | None = Field(None, description="User who last modified this evaluator")
    name: str | None = Field(None, description="User-defined name for the evaluator")
    organization_id: str | None = Field(None, description="Organization identifier")
    platform: str | None = Field(None, description="Platform type (e.g., Windows, Linux)")
    shutdown_status: str | None = Field(
        None,
        description="Status of evaluator shutdown (unset, normal, aborted, crash, failed). Default: unset",
    )
    user_id: str | None = Field(None, description="User ID authenticated with")
    username: str | None = Field(None, description="Username authenticated with")


class EvaluatorsBodyInputBody(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    evaluators: list[dict[str, Any]] | None


class EvaluatorsOutputBody(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    evaluators: list[EvaluatorRegistration] | None = Field(..., description="List of evaluators")


class Resources(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    custom: dict[str, Any] | None = Field(None, description="Custom resource attributes")
    disk_space: int | None = Field(None, description="Disk space in GB")
    memory: int | None = Field(None, description="Memory in GB")
    num_cores: int | None = Field(None, description="Number of CPU cores")
    num_instances: int | None = Field(None, description="Number of instances")
    platform: str | None = Field(None, description="Platform type")


class ScalerApplicationInfo(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    capabilities: list[str] | None = Field(None, description="Capabilities of the scaler")
    customization_hook: dict[str, Any] | None = Field(None, description="Customization hook")
    environment: dict[str, str] | None = Field(None, description="Environment variables")
    executable: str | None = Field(None, description="Executable name")
    install_path: str | None = Field(None, description="Installation path")
    local_scratch_dir: str | None = Field(None, description="Local scratch directory path")
    name: str | None = Field(None, description="Name of the scaler application")
    resource_name: str | None = Field(None, description="Resource name")
    use_local_scratch: bool | None = Field(None, description="Whether to use local scratch space")
    version: str | None = Field(None, description="Version of the scaler application")


class ScalerRegistration(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    account_id: str | None = Field(None, description="Account ID for multi-tenancy")
    build_info: dict[str, Any] | None = Field(None, description="Build version information")
    config_modified: datetime | None = Field(
        None,
        description="When the configuration was last modified (ISO 8601 timestamp)",
    )
    created_by: str | None = Field(None, description="User who created this scaler")
    host_id: str | None = Field(None, description="Host identifier where scaler is running")
    host_name: str | None = Field(None, description="Host name where scaler is running")
    id: str | None = Field(None, description="Unique identifier for the scaler")
    is_admin: bool | None = Field(None, description="Whether this scaler has admin privileges")
    last_modified: datetime | None = Field(None, description="Last modified timestamp")
    last_modified_by: str | None = Field(None, description="User who last modified this scaler")
    name: str | None = Field(None, description="User-defined name for the scaler")
    organization_id: str | None = Field(None, description="Organization identifier")
    platform: str | None = Field(None, description="Platform type (e.g., Windows, Linux)")
    user_id: str | None = Field(None, description="User ID authenticated with")
    username: str | None = Field(None, description="Username authenticated with")


class ScalersBodyInputBody(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scalers: list[dict[str, Any]] | None


class ScalersOutputBody(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scalers: list[ScalerRegistration] | None = Field(..., description="List of scalers")


class AnalyzeRequirements(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    evaluator_ids: list[str] | None = None
    project_id: str | None = None
    project_permissions: list[AnalyzePermission] | None = None
    resource_requirements: AnalyzeResourceRequirements | None = None
    scaler_ids: list[str] | None = None
    software_requirements: list[AnalyzeRequiredSoftware] | None = None


class AnalyzeResponseEvaluator(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    evaluator_id: str
    requirements: AnalyzeResponseRequirements | None = None
    resource_requirements: AnalyzeResourceRequirements
    software_requirements: list[AnalyzeRequiredSoftware] | None


class ComputeResourceSet(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    account_id: str | None = Field(None, description="Account ID for multi-tenancy")
    available_applications: list[ScalerApplicationInfo] | None = Field(
        None, description="List of scaler applications"
    )
    available_resources: Resources | None = Field(None, description="Hardware resources available")
    backend: dict[str, Any] | None = Field(None, description="Backend configuration")
    created_by: str | None = Field(None, description="User who created this compute resource set")
    evaluator_auto_shutdown_time: int | None = Field(
        None, description="Auto shutdown time for evaluators (seconds)"
    )
    evaluator_loop_interval: int | None = Field(
        None, description="Loop interval for evaluator checks (seconds)"
    )
    evaluator_requirements_matching: bool | None = Field(
        None, description="Whether evaluator requirements matching is enabled"
    )
    evaluator_task_directory_cleanup: str | None = Field(
        None,
        description="When to cleanup evaluator task directories: 'always', 'on_success', or 'never'",
    )
    id: str | None = Field(None, description="Unique identifier for the compute resource set")
    last_modified: datetime | None = Field(None, description="Last modified timestamp")
    last_modified_by: str | None = Field(
        None, description="User who last modified this compute resource set"
    )
    name: str | None = Field(None, description="User-defined name for the compute resource set")
    scaler_id: str | None = Field(None, description="Associated scaler identifier")
    scaling_strategy: dict[str, Any] | None = Field(
        None, description="Scaling strategy configuration"
    )


class ComputeResourceSetsOutputBody(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    compute_resource_sets: list[ComputeResourceSet] | None = Field(
        ..., description="List of compute resource sets"
    )


class AnalyzeResponseBody(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    analytics: AnalyticsData | None = None
    evaluators: list[AnalyzeResponseEvaluator] | None
    scalers: list[AnalyzeResponseScaler] | None
