# Copyright (C) 2022 - 2026 Synopsys, Inc. and ANSYS, Inc. All rights reserved.
# SPDX-License-Identifier: MIT
#
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# DO NOT EDIT.
# This file is automatically generated from the RMS OpenApi Specification
# using datamodel-code-generator.

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any

from pydantic import AnyUrl, ConfigDict, Field

from ansys.hps.client.common import DictModel


class AnalyticsData(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    number_accessible: int
    number_accessible_assignable_and_matching: int
    number_assignable: int
    number_matching: int


class AnalyzeHpcResources(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    exclusive: bool | None = None
    local_scratch_dir: str | None = None
    native_submit_options: str | None = None
    num_cores_per_node: int | None = None
    num_gpus_per_node: int | None = None
    queue: str | None = None
    use_local_scratch: bool | None = None


class AnalyzePermission(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    permission_type: str
    role: str
    value_id: str
    value_name: str


class AnalyzeRequiredSoftware(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    version: str | None = None


class Platform(Enum):
    windows = "windows"
    linux = "linux"
    darwin = "darwin"


class AnalyzeResourceRequirements(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    compute_resource_set_id: str | None = None
    custom: dict[str, Any] | None = None
    disk_space: int | None = None
    distributed: bool | None = None
    evaluator_id: str | None = None
    hpc_resources: AnalyzeHpcResources | None = None
    memory: int | None = None
    num_cores: float | None = None
    platform: Platform | None = None


class AnalyzeResponseRequirements(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    accessible: bool | None = None
    assignable: bool | None = None
    has_applications: bool | None = None
    has_custom: bool | None = None
    has_hardware: bool | None = None
    has_platform: bool | None = None


class AnalyzeResponseScaler(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    compute_resource_set_id: str
    requirements: AnalyzeResponseRequirements | None = None
    resource_requirements: AnalyzeResourceRequirements
    scaler_id: str
    software_requirements: list[AnalyzeRequiredSoftware] | None


class EvaluatorTaskDirectoryCleanup(Enum):
    always = "always"
    on_success = "on_success"
    never = "never"


class ConfigurationUpdateInput(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    applied: bool | None = Field(
        None, description="Whether the update has been applied. Default: false"
    )
    evaluator_id: str | None = Field(None, description="Evaluator identifier")
    id: str | None = Field(
        None,
        description="Optional unique identifier for the update (generated if not provided)",
    )
    update: dict[str, Any] | None = Field(None, description="Update data")


class ConfigurationUpdateOutput(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    applied: bool | None = Field(
        None, description="Whether the update has been applied. Default: false"
    )
    evaluator_id: str | None = Field(..., description="Evaluator identifier")
    id: str = Field(..., description="Unique identifier for the update")
    last_modified: datetime | None = Field(..., description="Last modified timestamp")
    update: dict[str, Any] = Field(..., description="Update data")


class ConfigurationUpdatesResponseBody(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    configuration_updates: list[ConfigurationUpdateOutput] | None = Field(
        ..., description="List of configuration updates"
    )


class DeleteResponseBody(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    deleted: int = Field(..., description="Number of resources deleted")


class ErrorDetail(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    location: str | None = Field(
        None,
        description="Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'",
    )
    message: str | None = Field(None, description="Error message text")
    value: Any | None = Field(None, description="The value at the given location")


class ErrorModel(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    detail: str | None = Field(
        None,
        description="A human-readable explanation specific to this occurrence of the problem.",
        examples=["Property foo is required but is missing."],
    )
    errors: list[ErrorDetail] | None = Field(
        None, description="Optional list of individual error details"
    )
    instance: AnyUrl | None = Field(
        None,
        description="A URI reference that identifies the specific occurrence of the problem.",
        examples=["https://example.com/error-log/abc123"],
    )
    status: int | None = Field(None, description="HTTP status code", examples=[400])
    title: str | None = Field(
        None,
        description="A short, human-readable summary of the problem type. This value should not change between occurrences of the error.",
        examples=["Bad Request"],
    )
    type: AnyUrl | None = Field(
        "about:blank",
        description="A URI reference to human-readable documentation for the error.",
        examples=["https://example.com/errors/example"],
    )


class EvaluatorConfiguration(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    configuration: dict[str, Any] = Field(..., description="Configuration data")
    evaluator_id: str | None = Field(..., description="Evaluator identifier")
    id: str = Field(..., description="Unique identifier for the configuration")
    last_modified: datetime | None = Field(..., description="Last modified timestamp")


class EvaluatorConfigurationUpdatesRequestBody(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    configuration_updates: list[ConfigurationUpdateInput] | None = Field(
        ..., description="List of configuration updates to create"
    )


class EvaluatorConfigurationsOutputBody(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    configurations: list[EvaluatorConfiguration] | None = Field(
        ..., description="List of evaluator configurations"
    )


class ShutdownStatus(Enum):
    unset = "unset"
    normal = "normal"
    aborted = "aborted"
    crash = "crash"
    failed = "failed"


class EvaluatorInput(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    account_id: str | None = Field(None, description="Account ID for multi-tenancy (read-only)")
    build_info: dict[str, Any] | None = Field(None, description="Build version information")
    change_requested: datetime | None = Field(
        None,
        description="When a configuration change was requested (ISO 8601 timestamp)",
    )
    compute_resource_set_id: str | None = Field(
        None, description="Associated compute resource set ID"
    )
    created_by: str | None = Field(None, description="User who created this evaluator (read-only)")
    host_id: str | None = Field(None, description="Host identifier where evaluator is running")
    host_name: str | None = Field(None, description="Host name where evaluator is running")
    house_cleaned: bool | None = Field(
        None,
        description="Flag indicating housekeeper has processed abnormal shutdown_status. Default: false",
    )
    id: str | None = Field(
        None,
        description="Optional unique identifier for the evaluator (generated if not provided)",
    )
    is_admin: bool | None = Field(None, description="Whether this evaluator has admin privileges")
    last_modified: datetime | None = Field(None, description="Last modified timestamp (read-only)")
    last_modified_by: str | None = Field(
        None, description="User who last modified this evaluator (read-only)"
    )
    name: str | None = Field(None, description="User-defined name for the evaluator")
    organization_id: str | None = Field(None, description="Organization identifier")
    platform: Platform | None = Field(None, description="Platform type (windows, linux, darwin)")
    project_assignment_mode: str | None = Field(
        None,
        description="How the evaluator selects projects to work on. Options: disabled, all_active, project_list",
    )
    project_list: list[str] | None = Field(
        None, description="IDs of projects that the evaluator should work on, in order"
    )
    shutdown_status: ShutdownStatus | None = Field(
        None,
        description="Status of evaluator shutdown (unset, normal, aborted, crash, failed). Default: unset",
    )
    user_id: str | None = Field(None, description="User ID authenticated with")
    username: str | None = Field(None, description="Username authenticated with")


class EvaluatorRegistrationOutput(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    account_id: str | None = Field(None, description="Account ID for multi-tenancy")
    build_info: dict[str, Any] | None = Field(None, description="Build version information")
    change_requested: datetime | None = Field(
        None,
        description="When a configuration change was requested (ISO 8601 timestamp)",
    )
    compute_resource_set_id: str | None = Field(
        None, description="Associated compute resource set ID"
    )
    created_by: str | None = Field(None, description="User who created this evaluator")
    host_id: str | None = Field(None, description="Host identifier where evaluator is running")
    host_name: str | None = Field(None, description="Host name where evaluator is running")
    house_cleaned: bool | None = Field(
        None,
        description="Flag indicating housekeeper has processed abnormal shutdown_status. Default: false",
    )
    id: str | None = Field(None, description="Unique identifier for the evaluator")
    is_admin: bool | None = Field(None, description="Whether this evaluator has admin privileges")
    last_modified: datetime | None = Field(None, description="Last modified timestamp")
    last_modified_by: str | None = Field(None, description="User who last modified this evaluator")
    name: str | None = Field(None, description="User-defined name for the evaluator")
    organization_id: str | None = Field(None, description="Organization identifier")
    platform: Platform | None = Field(None, description="Platform type (windows, linux, darwin)")
    project_assignment_mode: str | None = Field(
        None,
        description="How the evaluator selects projects to work on. Options: disabled, all_active, project_list",
    )
    project_list: list[str] | None = Field(
        None, description="IDs of projects that the evaluator should work on, in order"
    )
    shutdown_status: ShutdownStatus | None = Field(
        None,
        description="Status of evaluator shutdown (unset, normal, aborted, crash, failed). Default: unset",
    )
    user_id: str | None = Field(None, description="User ID authenticated with")
    username: str | None = Field(None, description="Username authenticated with")


class EvaluatorUpdate(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    account_id: str | None = Field(None, description="Account ID for multi-tenancy (read-only)")
    build_info: dict[str, Any] | None = Field(None, description="Build version information")
    change_requested: datetime | None = Field(
        None,
        description="When a configuration change was requested (ISO 8601 timestamp)",
    )
    compute_resource_set_id: str | None = Field(
        None, description="Associated compute resource set ID"
    )
    created_by: str | None = Field(None, description="User who created this evaluator (read-only)")
    host_id: str | None = Field(None, description="Host identifier where evaluator is running")
    host_name: str | None = Field(None, description="Host name where evaluator is running")
    house_cleaned: bool | None = Field(
        None,
        description="Flag indicating housekeeper has processed abnormal shutdown_status. Default: false",
    )
    id: str = Field(..., description="Unique identifier - required for PUT operations")
    is_admin: bool | None = Field(None, description="Whether this evaluator has admin privileges")
    last_modified: datetime | None = Field(None, description="Last modified timestamp (read-only)")
    last_modified_by: str | None = Field(
        None, description="User who last modified this evaluator (read-only)"
    )
    name: str | None = Field(None, description="User-defined name for the evaluator")
    organization_id: str | None = Field(None, description="Organization identifier")
    platform: Platform | None = Field(None, description="Platform type (windows, linux, darwin)")
    project_assignment_mode: str | None = Field(
        None,
        description="How the evaluator selects projects to work on. Options: disabled, all_active, project_list",
    )
    project_list: list[str] | None = Field(
        None, description="IDs of projects that the evaluator should work on, in order"
    )
    shutdown_status: ShutdownStatus | None = Field(
        None,
        description="Status of evaluator shutdown (unset, normal, aborted, crash, failed). Default: unset",
    )
    user_id: str | None = Field(None, description="User ID authenticated with")
    username: str | None = Field(None, description="Username authenticated with")


class EvaluatorsRequestBody(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    evaluators: list[EvaluatorInput] | None = Field(
        ..., description="List of evaluators to create or update"
    )


class EvaluatorsRequestForUpdateBody(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    evaluators: list[EvaluatorUpdate] | None = Field(
        ..., description="List of evaluators to update (ID required)"
    )


class EvaluatorsResponseBody(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    evaluators: list[EvaluatorRegistrationOutput] | None = Field(
        ..., description="List of evaluators"
    )


class NodeGroupInputFields(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    cores_per_node: int | None = Field(None, description="CPU cores available per node")
    memory_per_node_mb: int | None = Field(None, description="Memory available per node in MB")
    node_names: list[str] | None = Field(None, description="Names of nodes in this group")


class NodeGroupOutput(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    cores_per_node: int | None = Field(..., description="CPU cores available per node")
    memory_per_node_mb: int | None = Field(..., description="Memory available per node in MB")
    node_names: list[str] | None = Field(..., description="Names of nodes in this group")


class NodeInputFields(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    additional_props: dict[str, Any] | None = Field(None, description="Additional node properties")
    name: str | None = Field(None, description="Name of the node")
    reserved_cores: int | None = Field(None, description="Reserved CPU cores on the node")
    total_cores: int | None = Field(None, description="Total CPU cores on the node")
    total_memory_mb: int | None = Field(
        None, description="Total memory available on the node in MB"
    )
    used_memory_mb: int | None = Field(None, description="Used memory on the node in MB")


class NodeOutput(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    additional_props: dict[str, Any] = Field(..., description="Additional node properties")
    name: str | None = Field(..., description="Name of the node")
    reserved_cores: int | None = Field(..., description="Reserved CPU cores on the node")
    total_cores: int | None = Field(..., description="Total CPU cores on the node")
    total_memory_mb: int | None = Field(..., description="Total memory available on the node in MB")
    used_memory_mb: int | None = Field(..., description="Used memory on the node in MB")


class QueueInputFields(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    additional_props: dict[str, Any] | None = Field(None, description="Additional queue properties")
    name: str | None = Field(None, description="Name of the queue")
    node_groups: list[NodeGroupInputFields] | None = Field(
        None, description="List of node groups associated with the queue"
    )


class QueueLoad(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str | None = Field(..., description="Name of the queue")
    reserved_cores: int | None = Field(..., description="Reserved cores in this queue")
    total_cores: int | None = Field(..., description="Total cores allocated to this queue")
    total_memory_mb: int | None = Field(
        ..., description="Total memory allocated to this queue in MB"
    )
    used_memory_mb: int | None = Field(..., description="Used memory in this queue in MB")


class QueueOutput(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    additional_props: dict[str, Any] = Field(..., description="Additional queue properties")
    name: str | None = Field(..., description="Name of the queue")
    node_groups: list[NodeGroupOutput] | None = Field(
        ..., description="List of node groups associated with the queue"
    )


class ResourcesInputFields(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    custom: dict[str, Any] | None = Field(None, description="Custom resource attributes")
    disk_space: int | None = Field(None, description="Disk space in GB")
    memory: int | None = Field(None, description="Memory in GB")
    num_cores: int | None = Field(None, description="Number of CPU cores")
    num_instances: int | None = Field(None, description="Number of instances")
    platform: Platform | None = Field(None, description="Platform type (windows, linux, darwin)")


class ResourcesOutput(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    custom: dict[str, Any] = Field(..., description="Custom resource attributes")
    disk_space: int | None = Field(..., description="Disk space in GB")
    memory: int | None = Field(..., description="Memory in GB")
    num_cores: int | None = Field(..., description="Number of CPU cores")
    num_instances: int | None = Field(..., description="Number of instances")
    platform: Platform | None = Field(..., description="Platform type (windows, linux, darwin)")


class ScalerApplicationInfoInputFields(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    capabilities: list[str] | None = Field(None, description="Capabilities of the scaler")
    cool_down_period: int | None = Field(
        None, description="Cool down period between scale operations in seconds"
    )
    customization_hook: dict[str, Any] | None = Field(None, description="Customization hook")
    debug: bool | None = Field(None, description="Enable debug mode for the application")
    distributed: bool | None = Field(
        None, description="Whether the application supports distributed execution"
    )
    environment: dict[str, str] | None = Field(None, description="Environment variables")
    evaluator_image: str | None = Field(None, description="Docker image for evaluators")
    exclusive: bool | None = Field(
        None, description="Whether the application requires exclusive access"
    )
    executable: str | None = Field(None, description="Executable name")
    install_path: str | None = Field(None, description="Installation path")
    local_scratch_dir: str | None = Field(None, description="Local scratch directory path")
    name: str | None = Field(None, description="Name of the scaler application")
    queue: str | None = Field(None, description="Queue name for the application")
    resource_name: str | None = Field(None, description="Resource name")
    scaling_factor: float | None = Field(None, description="Scaling factor for scaling operations")
    scaling_max_eval_instances: int | None = Field(
        None, description="Maximum number of evaluator instances for scaling"
    )
    scaling_min_eval_instances: int | None = Field(
        None, description="Minimum number of evaluator instances for scaling"
    )
    scaling_threshold: int | None = Field(
        None, description="Scaling threshold for triggering scale operations"
    )
    use_local_scratch: bool | None = Field(None, description="Whether to use local scratch space")
    version: str | None = Field(None, description="Version of the scaler application")


class ScalerApplicationInfoOutput(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    capabilities: list[str] | None = Field(..., description="Capabilities of the scaler")
    cool_down_period: int | None = Field(
        ..., description="Cool down period between scale operations in seconds"
    )
    customization_hook: dict[str, Any] = Field(..., description="Customization hook")
    debug: bool | None = Field(None, description="Enable debug mode for the application")
    distributed: bool | None = Field(
        None, description="Whether the application supports distributed execution"
    )
    environment: dict[str, str] = Field(..., description="Environment variables")
    evaluator_image: str | None = Field(..., description="Docker image for evaluators")
    exclusive: bool | None = Field(
        None, description="Whether the application requires exclusive access"
    )
    executable: str | None = Field(..., description="Executable name")
    install_path: str | None = Field(..., description="Installation path")
    local_scratch_dir: str | None = Field(..., description="Local scratch directory path")
    name: str | None = Field(..., description="Name of the scaler application")
    queue: str | None = Field(..., description="Queue name for the application")
    resource_name: str | None = Field(..., description="Resource name")
    scaling_factor: float | None = Field(..., description="Scaling factor for scaling operations")
    scaling_max_eval_instances: int | None = Field(
        ..., description="Maximum number of evaluator instances for scaling"
    )
    scaling_min_eval_instances: int | None = Field(
        ..., description="Minimum number of evaluator instances for scaling"
    )
    scaling_threshold: int | None = Field(
        ..., description="Scaling threshold for triggering scale operations"
    )
    use_local_scratch: bool | None = Field(None, description="Whether to use local scratch space")
    version: str | None = Field(..., description="Version of the scaler application")


class ScalerInput(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    account_id: str | None = Field(None, description="Account ID for multi-tenancy (read-only)")
    build_info: dict[str, Any] | None = Field(None, description="Build version information")
    config_modified: datetime | None = Field(
        None,
        description="When the configuration was last modified (ISO 8601 timestamp)",
    )
    created_by: str | None = Field(None, description="User who created this scaler (read-only)")
    host_id: str | None = Field(None, description="Host identifier where scaler is running")
    host_name: str | None = Field(None, description="Host name where scaler is running")
    id: str | None = Field(
        None,
        description="Optional unique identifier for the scaler (generated if not provided)",
    )
    is_admin: bool | None = Field(None, description="Whether this scaler has admin privileges")
    last_modified: datetime | None = Field(None, description="Last modified timestamp (read-only)")
    last_modified_by: str | None = Field(
        None, description="User who last modified this scaler (read-only)"
    )
    name: str | None = Field(None, description="User-defined name for the scaler")
    organization_id: str | None = Field(None, description="Organization identifier")
    platform: Platform | None = Field(None, description="Platform type (windows, linux, darwin)")
    project_list: list[str] | None = Field(
        None, description="IDs of projects that the scaler should work on, in order"
    )
    user_id: str | None = Field(None, description="User ID authenticated with")
    username: str | None = Field(None, description="Username authenticated with")


class ScalerRegistrationOutput(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    account_id: str | None = Field(None, description="Account ID for multi-tenancy")
    build_info: dict[str, Any] | None = Field(None, description="Build version information")
    config_modified: datetime | None = Field(
        None,
        description="When the configuration was last modified (ISO 8601 timestamp)",
    )
    created_by: str | None = Field(None, description="User who created this scaler")
    host_id: str | None = Field(None, description="Host identifier where scaler is running")
    host_name: str | None = Field(None, description="Host name where scaler is running")
    id: str | None = Field(None, description="Unique identifier for the scaler")
    is_admin: bool | None = Field(None, description="Whether this scaler has admin privileges")
    last_modified: datetime | None = Field(None, description="Last modified timestamp")
    last_modified_by: str | None = Field(None, description="User who last modified this scaler")
    name: str | None = Field(None, description="User-defined name for the scaler")
    organization_id: str | None = Field(None, description="Organization identifier")
    platform: Platform | None = Field(None, description="Platform type (windows, linux, darwin)")
    project_list: list[str] | None = Field(
        None, description="IDs of projects that the scaler should work on, in order"
    )
    user_id: str | None = Field(None, description="User ID authenticated with")
    username: str | None = Field(None, description="Username authenticated with")


class ScalerUpdate(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    account_id: str | None = Field(None, description="Account ID for multi-tenancy (read-only)")
    build_info: dict[str, Any] | None = Field(None, description="Build version information")
    config_modified: datetime | None = Field(
        None,
        description="When the configuration was last modified (ISO 8601 timestamp)",
    )
    created_by: str | None = Field(None, description="User who created this scaler (read-only)")
    host_id: str | None = Field(None, description="Host identifier where scaler is running")
    host_name: str | None = Field(None, description="Host name where scaler is running")
    id: str = Field(..., description="Unique identifier - required for PUT operations")
    is_admin: bool | None = Field(None, description="Whether this scaler has admin privileges")
    last_modified: datetime | None = Field(None, description="Last modified timestamp (read-only)")
    last_modified_by: str | None = Field(
        None, description="User who last modified this scaler (read-only)"
    )
    name: str | None = Field(None, description="User-defined name for the scaler")
    organization_id: str | None = Field(None, description="Organization identifier")
    platform: Platform | None = Field(None, description="Platform type (windows, linux, darwin)")
    project_list: list[str] | None = Field(
        None, description="IDs of projects that the scaler should work on, in order"
    )
    user_id: str | None = Field(None, description="User ID authenticated with")
    username: str | None = Field(None, description="Username authenticated with")


class ScalersRequestBody(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scalers: list[ScalerInput] | None = Field(
        ..., description="List of scalers to create or update"
    )


class ScalersRequestForUpdateBody(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scalers: list[ScalerUpdate] | None = Field(
        ..., description="List of scalers to update (ID required)"
    )


class ScalersResponseBody(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scalers: list[ScalerRegistrationOutput] | None = Field(..., description="List of scalers")


class AnalyzeRequirements(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    evaluator_ids: list[str] | None = None
    project_id: str | None = None
    project_permissions: list[AnalyzePermission] | None = None
    resource_requirements: AnalyzeResourceRequirements | None = None
    scaler_ids: list[str] | None = None
    software_requirements: list[AnalyzeRequiredSoftware] | None = None


class AnalyzeResponseEvaluator(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    evaluator_id: str
    requirements: AnalyzeResponseRequirements | None = None
    resource_requirements: AnalyzeResourceRequirements
    software_requirements: list[AnalyzeRequiredSoftware] | None


class ClusterInfoInput(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    additional_props: dict[str, Any] | None = Field(
        None, description="Additional cluster properties"
    )
    crs_id: str | None = Field(None, description="Compute resource set ID")
    id: str | None = Field(
        None,
        description="Optional unique identifier for the cluster info (generated if not provided)",
    )
    name: str | None = Field(None, description="Cluster name")
    nodes: list[NodeInputFields] | None = Field(None, description="List of compute nodes")
    queues: list[QueueInputFields] | None = Field(None, description="List of compute queues")


class ClusterInfoOutput(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    additional_props: dict[str, Any] = Field(..., description="Additional cluster properties")
    crs_id: str | None = Field(..., description="Compute resource set ID")
    id: str | None = Field(..., description="Unique ID for the cluster info")
    name: str | None = Field(..., description="Cluster name")
    nodes: list[NodeOutput] | None = Field(..., description="List of compute nodes")
    queues: list[QueueOutput] | None = Field(..., description="List of compute queues")


class ClusterLoadSnapshot(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    crs_id: str | None = Field(..., description="Compute resource set ID")
    id: str | None = Field(..., description="Unique ID for the cluster load snapshot")
    queue_loads: list[QueueLoad] | None = Field(..., description="List of queue load information")
    timestamp: datetime | None = Field(..., description="Timestamp of this load data")


class ComputeResourceSetInput(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    account_id: str | None = Field(None, description="Account ID for multi-tenancy (read-only)")
    available_applications: list[ScalerApplicationInfoInputFields] | None = Field(
        None, description="List of scaler applications"
    )
    available_resources: ResourcesInputFields | None = Field(
        None, description="Hardware resources available"
    )
    backend: dict[str, Any] | None = Field(None, description="Backend configuration")
    created_by: str | None = Field(
        None, description="User who created this compute resource set (read-only)"
    )
    evaluator_auto_shutdown_time: int | None = Field(
        None, description="Auto shutdown time for evaluators (seconds)"
    )
    evaluator_loop_interval: int | None = Field(
        None, description="Loop interval for evaluator checks (seconds)"
    )
    evaluator_optimized_move: bool | None = Field(
        None, description="Whether to use optimized move for evaluators"
    )
    evaluator_requirements_matching: bool | None = Field(
        None, description="Whether evaluator requirements matching is enabled"
    )
    evaluator_task_directory_cleanup: EvaluatorTaskDirectoryCleanup | None = Field(
        None,
        description="When to cleanup evaluator task directories: always, on_success, or never",
    )
    last_modified: datetime | None = Field(None, description="Last modified timestamp (read-only)")
    last_modified_by: str | None = Field(
        None, description="User who last modified this compute resource set (read-only)"
    )
    name: str | None = Field(None, description="User-defined name for the compute resource set")
    scaler_id: str | None = Field(None, description="Associated scaler identifier")
    scaling_strategy: dict[str, Any] | None = Field(
        None, description="Scaling strategy configuration"
    )


class ComputeResourceSetOutput(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    account_id: str | None = Field(None, description="Account ID for multi-tenancy")
    available_applications: list[ScalerApplicationInfoOutput] | None = Field(
        None, description="List of scaler applications"
    )
    available_resources: ResourcesOutput | None = Field(
        None, description="Hardware resources available"
    )
    backend: dict[str, Any] | None = Field(None, description="Backend configuration")
    created_by: str | None = Field(None, description="User who created this compute resource set")
    evaluator_auto_shutdown_time: int | None = Field(
        None, description="Auto shutdown time for evaluators (seconds)"
    )
    evaluator_loop_interval: int | None = Field(
        None, description="Loop interval for evaluator checks (seconds)"
    )
    evaluator_optimized_move: bool | None = Field(
        None, description="Whether to use optimized move for evaluators"
    )
    evaluator_requirements_matching: bool | None = Field(
        None, description="Whether evaluator requirements matching is enabled"
    )
    evaluator_task_directory_cleanup: EvaluatorTaskDirectoryCleanup | None = Field(
        None,
        description="When to cleanup evaluator task directories: always, on_success, or never",
    )
    id: str | None = Field(None, description="Unique identifier for the compute resource set")
    last_modified: datetime | None = Field(None, description="Last modified timestamp")
    last_modified_by: str | None = Field(
        None, description="User who last modified this compute resource set"
    )
    name: str | None = Field(None, description="User-defined name for the compute resource set")
    scaler_id: str | None = Field(None, description="Associated scaler identifier")
    scaling_strategy: dict[str, Any] | None = Field(
        None, description="Scaling strategy configuration"
    )


class ComputeResourceSetUpdate(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    account_id: str | None = Field(None, description="Account ID for multi-tenancy (read-only)")
    available_applications: list[ScalerApplicationInfoInputFields] | None = Field(
        None, description="List of scaler applications"
    )
    available_resources: ResourcesInputFields | None = Field(
        None, description="Hardware resources available"
    )
    backend: dict[str, Any] | None = Field(None, description="Backend configuration")
    created_by: str | None = Field(
        None, description="User who created this compute resource set (read-only)"
    )
    evaluator_auto_shutdown_time: int | None = Field(
        None, description="Auto shutdown time for evaluators (seconds)"
    )
    evaluator_loop_interval: int | None = Field(
        None, description="Loop interval for evaluator checks (seconds)"
    )
    evaluator_optimized_move: bool | None = Field(
        None, description="Whether to use optimized move for evaluators"
    )
    evaluator_requirements_matching: bool | None = Field(
        None, description="Whether evaluator requirements matching is enabled"
    )
    evaluator_task_directory_cleanup: EvaluatorTaskDirectoryCleanup | None = Field(
        None,
        description="When to cleanup evaluator task directories: always, on_success, or never",
    )
    id: str = Field(..., description="Unique identifier - required for PUT operations")
    last_modified: datetime | None = Field(None, description="Last modified timestamp (read-only)")
    last_modified_by: str | None = Field(
        None, description="User who last modified this compute resource set (read-only)"
    )
    name: str | None = Field(None, description="User-defined name for the compute resource set")
    scaler_id: str | None = Field(None, description="Associated scaler identifier")
    scaling_strategy: dict[str, Any] | None = Field(
        None, description="Scaling strategy configuration"
    )


class ComputeResourceSetsRequestBody(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    compute_resource_sets: list[ComputeResourceSetInput] | None = Field(
        ..., description="List of compute resource sets to create or update"
    )


class ComputeResourceSetsRequestForUpdateBody(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    compute_resource_sets: list[ComputeResourceSetUpdate] | None = Field(
        ..., description="List of compute resource sets to update (ID required)"
    )


class ComputeResourceSetsResponseBody(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    compute_resource_sets: list[ComputeResourceSetOutput] | None = Field(
        ..., description="List of compute resource sets"
    )


class ScalersInfoResponseBody(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    compute_resources: list[ComputeResourceSetOutput] | None = Field(
        ..., description="List of compute resource sets linked by scaler_id"
    )
    queue_info: list[ClusterInfoOutput] | None = Field(
        ..., description="List of cluster queue information"
    )
    scalers: list[ScalerRegistrationOutput] | None = Field(..., description="List of scalers")


class AnalyzeResponseBody(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    analytics: AnalyticsData | None = None
    evaluators: list[AnalyzeResponseEvaluator] | None
    scalers: list[AnalyzeResponseScaler] | None


class ClusterInfoItemResponseBody(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    cluster_info: ClusterInfoOutput = Field(..., description="Cluster information details")


class ClusterLoadHistoryResponseBody(DictModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    cluster_load_history: list[ClusterLoadSnapshot] | None = Field(
        ..., description="Cluster load history"
    )
