"""
Automation script to generate the hash for the example data files
"""

import json
import os

import pooch

data_dir = os.path.join(".", "examples", "data")
registry_file = os.path.join(".", "ansys", "rep", "client", "examples_data", "_registry.py")
files = [f for f in os.listdir(data_dir) if os.path.isfile(os.path.join(data_dir, f))]

registry = {}
for file in files:
    hash = pooch.file_hash(os.path.join(data_dir, file))
    print(f"Adding {file} with hash {hash}")
    registry[file] = hash

registry_string = json.dumps(registry, indent=2)
print(f"Hash registry saved to {registry_file}")

with open(registry_file, "w") as f:
    f.write(f"# autogenerated registry of file hashes\n")
    f.write(f"registry = {registry_string}")
