# autogenerated code
from marshmallow.utils import missing
from ansys.rep.client.common import Object
from ..schema.user import UserSchema

class User(Object):
    """User resource.

    Parameters
    ----------
    id : str
        Unique user ID, generated internally by the server on creation.
    username : str
        Username.
    password : str
        Password.
    first_name : str, optional
        First name
    last_name : str, optional
        Last name
    email : str, optional
        E-mail address (optional).
    groups : str
        Groups the user belongs to
    realm_roles : str
        Realm roles assigned to the user
    is_admin        Whether the user has admin rights or not.

    """

    class Meta:
        schema = UserSchema
        rest_name = "None"

    def __init__(self,
        id=missing,
        username=missing,
        password=missing,
        first_name=missing,
        last_name=missing,
        email=missing,
        groups=missing,
        realm_roles=missing,
        is_admin=missing
    ):
        self.id = id
        self.username = username
        self.password = password
        self.first_name = first_name
        self.last_name = last_name
        self.email = email
        self.groups = groups
        self.realm_roles = realm_roles
        self.is_admin = is_admin

        self.obj_type = self.__class__.__name__

UserSchema.Meta.object_class = User
