# autogenerated code
from marshmallow.utils import missing
from ansys.rep.client.common import Object
from ..schema.algorithm import AlgorithmSchema

class Algorithm(Object):
    """Algorithm resource.

    Parameters
    ----------
    id : str, optional
        Unique ID to access the resource, generated internally by the server on creation.
    name : str, optional
        Name of the algorithm.
    description : str, optional
        Description of the algorithm.
    creation_time : datetime, optional
        The date and time the algorithm was created.
    modification_time : datetime, optional
        The date and time the algorithm was last modified.
    data : str, optional
        Generic string field to hold arbitrary algorithm configuration data, e.g. as JSON dictionary.
    jobs : list[str]
        List of job IDs.

    """

    class Meta:
        schema = AlgorithmSchema
        rest_name = "algorithms"

    def __init__(self,
        id=missing,
        name=missing,
        description=missing,
        creation_time=missing,
        modification_time=missing,
        data=missing,
        jobs=missing
    ):
        self.id = id
        self.name = name
        self.description = description
        self.creation_time = creation_time
        self.modification_time = modification_time
        self.data = data
        self.jobs = jobs

        self.obj_type = self.__class__.__name__

AlgorithmSchema.Meta.object_class = Algorithm
