# autogenerated code
from marshmallow.utils import missing
from ansys.rep.client.common import Object
from ..schema.evaluator import EvaluatorConfigurationUpdateSchema
from ..schema.evaluator import EvaluatorSchema

class EvaluatorConfigurationUpdate(Object):
    """EvaluatorConfigurationUpdate resource.

    Parameters
    ----------
    id : str, optional
        Unique ID to access the resource, generated internally by the server on creation.
    name : str, optional
    applications : list, optional
    max_num_parallel_tasks : int, optional
    loop_interval : float, optional
    working_directory : str, optional
    local_file_cache : bool, optional
    local_file_cache_max_size : int, optional
    task_directory_cleanup : str, optional
    custom_resource_properties : dict, optional

    """

    class Meta:
        schema = EvaluatorConfigurationUpdateSchema
        rest_name = "configuration"

    def __init__(self,
        id=missing,
        name=missing,
        applications=missing,
        max_num_parallel_tasks=missing,
        loop_interval=missing,
        working_directory=missing,
        local_file_cache=missing,
        local_file_cache_max_size=missing,
        task_directory_cleanup=missing,
        custom_resource_properties=missing
    ):
        self.id = id
        self.name = name
        self.applications = applications
        self.max_num_parallel_tasks = max_num_parallel_tasks
        self.loop_interval = loop_interval
        self.working_directory = working_directory
        self.local_file_cache = local_file_cache
        self.local_file_cache_max_size = local_file_cache_max_size
        self.task_directory_cleanup = task_directory_cleanup
        self.custom_resource_properties = custom_resource_properties

        self.obj_type = self.__class__.__name__

EvaluatorConfigurationUpdateSchema.Meta.object_class = EvaluatorConfigurationUpdate

class Evaluator(Object):
    """Evaluator resource.

    Parameters
    ----------
    id : str, optional
        Unique ID to access the resource, generated internally by the server on creation.
    host_id : str
        Unique identifier built from hardware information and selected configuration details of an evaluator.
    name : str, optional
        Name of the evaluator.
    hostname : str, optional
        Name of the host on which the evaluator is running.
    platform : str, optional
        Operating system on which the evaluator is running.
    task_manager_type : str, optional
        Type of the task manager used by the evaluator.
    project_server_select : bool, optional
        Whether the evaluator allows server-driven assignment of projects or uses it's own local settings.
    alive_update_interval : int, optional
        Minimal time (in seconds) between evaluator registration updates.
    update_time : datetime, optional
        Last time the evaluator updated it's registration details. Used to check which evaluators are alive.
    external_access_port : int, optional
        Port number for external access to the evaluator.
    project_assignment_mode : str, optional
        Which strategy to use for selecting projects to work on.
    project_list : list
        List of projects on which this evaluator should be working.
    configuration : dict, optional
        Details of the evaluator configuration, including hardware info and available applications.
    configuration_updates : EvaluatorConfigurationUpdate, optional
        Changes to the evaluator configurations.

    """

    class Meta:
        schema = EvaluatorSchema
        rest_name = "evaluators"

    def __init__(self,
        id=missing,
        host_id=missing,
        name=missing,
        hostname=missing,
        platform=missing,
        task_manager_type=missing,
        project_server_select=missing,
        alive_update_interval=missing,
        update_time=missing,
        external_access_port=missing,
        project_assignment_mode=missing,
        project_list=missing,
        configuration=missing,
        configuration_updates=missing
    ):
        self.id = id
        self.host_id = host_id
        self.name = name
        self.hostname = hostname
        self.platform = platform
        self.task_manager_type = task_manager_type
        self.project_server_select = project_server_select
        self.alive_update_interval = alive_update_interval
        self.update_time = update_time
        self.external_access_port = external_access_port
        self.project_assignment_mode = project_assignment_mode
        self.project_list = project_list
        self.configuration = configuration
        self.configuration_updates = configuration_updates

        self.obj_type = self.__class__.__name__

EvaluatorSchema.Meta.object_class = Evaluator
