# autogenerated code
from marshmallow.utils import missing
from ansys.rep.client.common import Object
from ..schema.job_definition import JobDefinitionSchema

class JobDefinition(Object):
    """JobDefinition resource.

    Parameters
    ----------
    id : str, optional
        Unique ID to access the resource, generated internally by the server on creation.
    creation_time : datetime, optional
        The date and time the resource was created.
    modification_time : datetime, optional
        The date and time the resource was last modified.
    created_by : str, optional
        ID of the user who created the object.
    modified_by : str, optional
        ID of the user who last modified the object.
    name : str, optional
        Name of the job definition
    active : bool
        Defines whether this is the active job definition in the project where evaluators will evaluate pending jobs
    client_hash : str, optional
    parameter_definition_ids : list[str]
    parameter_mapping_ids : list[str]
    task_definition_ids : list[str]
    fitness_definition : FitnessDefinitionBase, optional
        A :class:`FitnessDefinition` object.

    """

    class Meta:
        schema = JobDefinitionSchema
        rest_name = "job_definitions"

    def __init__(self,
        id=missing,
        creation_time=missing,
        modification_time=missing,
        created_by=missing,
        modified_by=missing,
        name=missing,
        active=missing,
        client_hash=missing,
        parameter_definition_ids=missing,
        parameter_mapping_ids=missing,
        task_definition_ids=missing,
        fitness_definition=missing
    ):
        self.id = id
        self.creation_time = creation_time
        self.modification_time = modification_time
        self.created_by = created_by
        self.modified_by = modified_by
        self.name = name
        self.active = active
        self.client_hash = client_hash
        self.parameter_definition_ids = parameter_definition_ids
        self.parameter_mapping_ids = parameter_mapping_ids
        self.task_definition_ids = task_definition_ids
        self.fitness_definition = fitness_definition

        self.obj_type = self.__class__.__name__

JobDefinitionSchema.Meta.object_class = JobDefinition
