# autogenerated code
from marshmallow.utils import missing
from ansys.rep.client.common import Object
from ..schema.parameter_mapping import ParameterMappingSchema

class ParameterMapping(Object):
    """ParameterMapping resource.

    Parameters
    ----------
    id : str, optional
        Unique ID to access the resource, generated internally by the server on creation.
    line : int, optional
    column : int, optional
    key_string : str, optional
    float_field : str, optional
    width : int, optional
    precision : int, optional
    tokenizer : str, optional
    decimal_symbol : str, optional
    digit_grouping_symbol : str, optional
    string_quote : str, optional
    true_string : str, optional
    false_string : str, optional
    parameter_definition_id : str, optional
        ID of the linked parameter definition, see :class:`ParameterDefinition`.
    task_definition_property : str, optional
    file_id : str, optional
        ID of the file resource.

    """

    class Meta:
        schema = ParameterMappingSchema
        rest_name = "parameter_mappings"

    def __init__(self,
        id=missing,
        line=missing,
        column=missing,
        key_string=missing,
        float_field=missing,
        width=missing,
        precision=missing,
        tokenizer=missing,
        decimal_symbol=missing,
        digit_grouping_symbol=missing,
        string_quote=missing,
        true_string=missing,
        false_string=missing,
        parameter_definition_id=missing,
        task_definition_property=missing,
        file_id=missing
    ):
        self.id = id
        self.line = line
        self.column = column
        self.key_string = key_string
        self.float_field = float_field
        self.width = width
        self.precision = precision
        self.tokenizer = tokenizer
        self.decimal_symbol = decimal_symbol
        self.digit_grouping_symbol = digit_grouping_symbol
        self.string_quote = string_quote
        self.true_string = true_string
        self.false_string = false_string
        self.parameter_definition_id = parameter_definition_id
        self.task_definition_property = task_definition_property
        self.file_id = file_id

        self.obj_type = self.__class__.__name__

ParameterMappingSchema.Meta.object_class = ParameterMapping
