# autogenerated code
from marshmallow.utils import missing
from ansys.rep.client.common import Object
from ..schema.permission import PermissionSchema

class Permission(Object):
    """Permission resource.

    Parameters
    ----------
    permission_type : str
        Either 'user', 'group', or 'anyone'.
    value_id : str, optional
        Can be the ID of a user or group.
    value_name : str, optional
    role : str
        Either 'admin', 'writer',  or 'reader'.

    """

    class Meta:
        schema = PermissionSchema
        rest_name = "permissions"

    def __init__(self,
        permission_type=missing,
        value_id=missing,
        value_name=missing,
        role=missing
    ):
        self.permission_type = permission_type
        self.value_id = value_id
        self.value_name = value_name
        self.role = role

        self.obj_type = self.__class__.__name__

PermissionSchema.Meta.object_class = Permission
