# autogenerated code
from marshmallow.utils import missing
from ansys.rep.client.common import Object
from ..schema.project import ProjectSchema

class Project(Object):
    """Project resource.

    Parameters
    ----------
    id : str
        Unique ID to access the project, specified on creation of the project.
    name : str
        Name of the project.
    active : bool
        Defines whether the project is active for evaluation.
    priority : int
        Priority to pick the project for evaluation.
    creation_time : datetime, optional
        The date and time the project was created.
    modification_time : datetime, optional
        The date and time the project was last modified.
    statistics : dict
        Optional dictionary containing various project statistics.

    """

    class Meta:
        schema = ProjectSchema
        rest_name = "projects"

    def __init__(self,
        id=missing,
        name=missing,
        active=missing,
        priority=missing,
        creation_time=missing,
        modification_time=missing,
        statistics=missing,
        **kwargs
    ):
        self.id = id
        self.name = name
        self.active = active
        self.priority = priority
        self.creation_time = creation_time
        self.modification_time = modification_time
        self.statistics = statistics

        self.obj_type = self.__class__.__name__

ProjectSchema.Meta.object_class = Project
