# autogenerated code
from marshmallow.utils import missing
from ansys.rep.client.common import Object
from ..schema.project_permission import ProjectPermissionSchema

class ProjectPermission(Object):
    """ProjectPermission resource.

    Parameters
    ----------
    permission_type : str
    value_id : str
    value_name : str, optional
    role : str

    """

    class Meta:
        schema = ProjectPermissionSchema
        rest_name = "permissions"

    def __init__(self,
        permission_type=missing,
        value_id=missing,
        value_name=missing,
        role=missing
    ):
        self.permission_type = permission_type
        self.value_id = value_id
        self.value_name = value_name
        self.role = role

        self.obj_type = self.__class__.__name__

ProjectPermissionSchema.Meta.object_class = ProjectPermission
