# autogenerated code based on TemplateResourceRequirementsSchema

from marshmallow.utils import missing
from ansys.rep.client.common import Object
from ..schema.task_definition_template import TemplateResourceRequirementsSchema

class TemplateResourceRequirements(Object):
    """TemplateResourceRequirements resource.

    Parameters
    ----------
    platform : TemplateProperty, optional
    memory : TemplateProperty, optional
    cpu_core_usage : TemplateProperty, optional
    disk_space : TemplateProperty, optional
    custom : dict, optional

    """

    class Meta:
        schema = TemplateResourceRequirementsSchema
        rest_name = "None"

    def __init__(self, **kwargs):
        self.platform = missing
        self.memory = missing
        self.cpu_core_usage = missing
        self.disk_space = missing
        self.custom = missing

        super().__init__(**kwargs)

TemplateResourceRequirementsSchema.Meta.object_class = TemplateResourceRequirements
