# autogenerated code based on TemplateOutputFileSchema

from marshmallow.utils import missing
from ansys.rep.client.common import Object
from ..schema.task_definition_template import TemplateOutputFileSchema

class TemplateOutputFile(Object):
    """TemplateOutputFile resource.

    Parameters
    ----------
    name : str
        Name of the file.
    type : str, optional
        MIME type of the file, ie. text/plain.
    evaluation_path : str, optional
        Path under which the file is expected to be found during evaluation.
    description : str
        Description of the file's purpose.
    monitor : bool, optional
        Should the file's contents be live monitored
    collect : bool, optional
        Should files be collected per job

    """

    class Meta:
        schema = TemplateOutputFileSchema
        rest_name = "None"

    def __init__(self, **kwargs):
        self.name = missing
        self.type = missing
        self.evaluation_path = missing
        self.description = missing
        self.monitor = missing
        self.collect = missing

        super().__init__(**kwargs)

TemplateOutputFileSchema.Meta.object_class = TemplateOutputFile
