# autogenerated code based on TemplateInputFileSchema

from marshmallow.utils import missing
from ansys.rep.client.common import Object
from ..schema.task_definition_template import TemplateInputFileSchema

class TemplateInputFile(Object):
    """TemplateInputFile resource.

    Parameters
    ----------
    name : str
        Name of the file.
    type : str, optional
        MIME type of the file, ie. text/plain.
    evaluation_path : str, optional
        Path under which the file is expected to be found during evaluation.
    description : str
        Description of the file's purpose.

    """

    class Meta:
        schema = TemplateInputFileSchema
        rest_name = "None"

    def __init__(self, **kwargs):
        self.name = missing
        self.type = missing
        self.evaluation_path = missing
        self.description = missing

        super().__init__(**kwargs)

TemplateInputFileSchema.Meta.object_class = TemplateInputFile
