# autogenerated code based on TemplatePropertySchema

from marshmallow.utils import missing
from ansys.rep.client.common import Object
from ..schema.task_definition_template import TemplatePropertySchema

class TemplateProperty(Object):
    """TemplateProperty resource.

    Parameters
    ----------
    default : any, optional
    description : str, optional
    type : str, optional

    """

    class Meta:
        schema = TemplatePropertySchema
        rest_name = "None"

    def __init__(self, **kwargs):
        self.default = missing
        self.description = missing
        self.type = missing

        super().__init__(**kwargs)

TemplatePropertySchema.Meta.object_class = TemplateProperty
