# autogenerated code
from marshmallow.utils import missing
from ansys.rep.client.common import Object
from ..schema.selection import JobSelectionSchema

class JobSelection(Object):
    """JobSelection resource.

    Parameters
    ----------
    id : str, optional
        Unique ID to access the resource, generated internally by the server on creation.
    creation_time : datetime, optional
        The date and time the resource was created.
    modification_time : datetime, optional
        The date and time the resource was last modified.
    created_by : str, optional
        ID of the user who created the object.
    modified_by : str, optional
        ID of the user who last modified the object.
    name : str
        Name of the selection.
    algorithm_id : str, optional
        ID of the :class:`Algorithm` the selection belongs to (optional).
    jobs : list[str]
        List of job IDs.

    """

    class Meta:
        schema = JobSelectionSchema
        rest_name = "job_selections"

    def __init__(self,
        id=missing,
        creation_time=missing,
        modification_time=missing,
        created_by=missing,
        modified_by=missing,
        name=missing,
        algorithm_id=missing,
        jobs=missing,
        **kwargs
    ):
        self.id = id
        self.creation_time = creation_time
        self.modification_time = modification_time
        self.created_by = created_by
        self.modified_by = modified_by
        self.name = name
        self.algorithm_id = algorithm_id
        self.jobs = jobs

        self.obj_type = self.__class__.__name__

JobSelectionSchema.Meta.object_class = JobSelection
