# Copyright (C) 2022 - 2026 ANSYS, Inc. and/or its affiliates.
# SPDX-License-Identifier: MIT
#
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# DO NOT EDIT.
# This file is automatically generated from the RMS OpenApi Specification
# using datamodel-code-generator.

from __future__ import annotations

from pydantic import Field

from ansys.hps.client.common import DictModel


class RegisterInstance(DictModel):
    """Register a new instance route."""

    url: str = Field(
        ...,
        description="(UI) URL of the instance/solution (e.g. http://ip.address:port)",
        title="Url",
    )
    api_url: str | None = Field(
        None,
        description="API URL of the instance/solution if any (optional) (e.g. http://ip.address:port)",
        title="Api Url",
    )
    service_name: str | None = Field(
        None, description="Service name to be used in the URL (optional)", title="Service Name"
    )
    project_url_sub_path: str | None = Field(
        None,
        description="URL subpath path of the project if any (optional) (e.g. /projects/1234)",
        title="Project Url Sub Path",
    )
    jms_project_id: str | None = Field(
        None,
        description=(
            "JMS project ID (optional). Passing this will create a URL with the project ID "
            "as a subpath rather than a random UID query parameter"
        ),
        title="Jms Project Id",
    )
    jms_job_id: str | None = Field(
        None, description="JMS job ID (optional) (e.g. 5678)", title="Jms Job Id"
    )
    jms_task_id: str | None = Field(
        None, description="JMS task ID (optional) (e.g. 91011)", title="Jms Task Id"
    )
    routing: str | None = Field(
        None,
        description=(
            "Routing used when using skip_oauth2_proxy. "
            "`query`: The instance is added as a query parameter (?ans_instance_id=xxx). "
            "`path_prefix`: The instance is added in the path (/ans_instance_id/xxx)."
        ),
        title="Routing",
    )


class UnRegisterInstance(DictModel):
    """Unregister an instance route."""

    resource_name: str = Field(
        ...,
        description="Resource name to unregister (short UID returned during registration)",
        title="Resource Name",
    )


class UnRegisterInstanceResponse(DictModel):
    """Response after unregistering an instance route."""

    message: str = Field(..., title="Message")
    resource_name: str = Field(..., title="Resource Name")


class RegisterInstanceResponse(DictModel):
    """Redis instance route information."""

    instance_url: str = Field(..., title="Instance Url")
    resource_name: str = Field(..., title="Resource Name")
