# autogenerated code
from marshmallow.utils import missing
from ansys.rep.client.common import Object
from ..schema.user import UserSchema

class User(Object):
    """User resource.

    Parameters
    ----------
    id : str
        Unique user ID, generated internally by the server on creation.
    username : str
        Username.
    password : str
        Password.
    first_name : str, optional
        First name
    last_name : str, optional
        Last name
    email : str, optional
        E-mail address (optional).

    """

    class Meta:
        schema = UserSchema
        rest_name = "None"

    def __init__(self,
        id=missing,
        username=missing,
        password=missing,
        first_name=missing,
        last_name=missing,
        email=missing,
        **kwargs
    ):
        self.id = id
        self.username = username
        self.password = password
        self.first_name = first_name
        self.last_name = last_name
        self.email = email

        self.obj_type = self.__class__.__name__

UserSchema.Meta.object_class = User
