name: Nightly Build
on:
  workflow_dispatch:
  schedule:
  - cron: "0 2 * * 1-5"

env:
  MAIN_PYTHON_VERSION: '3.7'
  DOC_PYTHON_VERSION: '3.9'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  style:
    name: Code style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools tox
      - name: Test with tox
        run: tox -e style

  quick-tests:
    name: Quick tests and coverage
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # extend to windows once it's possible to run docker 
        # on windows runners:
        # os: [windows-latest, ubuntu-latest]
        os: [ubuntu-latest]
        cfg:
          - {python-version: "3.7", toxenv: "py37"}
          - {python-version: "3.10", toxenv: "py310"}
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.cfg.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.cfg.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools tox tox-gh-actions

      - name: Check out rep-deployments
        uses: actions/checkout@v3
        with:
          repository: ansys/rep-deployments
          token: ${{ secrets.PYANSYS_CI_BOT_TOKEN }}
          submodules: true
          path: rep-deployments

      - uses: KengoTODA/actions-setup-docker-compose@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Login in Github Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: pyansys-ci-bot
          password: ${{ secrets.PYANSYS_CI_BOT_PACKAGE_TOKEN }}

      - name: Start services
        run: |
          docker-compose pull
          LOCALHOST_ADDR=localhost docker-compose up -d keycloak
          echo "Waiting a few sec ..."
          sleep 5
          LOCALHOST_ADDR=localhost docker-compose up -d
        working-directory: ./rep-deployments/docker-compose

      - name: Test with tox
        run: tox -e ${{ matrix.cfg.toxenv }}-noeval-coverage 
        env:
          REP_TEST_URL: https://localhost:8443/rep
          REP_TEST_USERNAME: repadmin
          REP_TEST_PASSWORD: repadmin

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: '**/test*.xml'
          check_name: Test Report ${{ matrix.os }}:${{ matrix.cfg.python-version }} 

  end-to-end-tests:
    name: End-to-end tests
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ env.MAIN_PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools tox tox-gh-actions

      - name: Test with tox
        run: tox -e py37-witheval 
        env:
          REP_TEST_URL: https://repkube.westeurope.cloudapp.azure.com/dev/rep
          REP_TEST_USERNAME: repbuild
          REP_TEST_PASSWORD: repbuild
          
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: '**/test*.xml'
          check_name: End-to-end Test Report 

  docs:
    name: Documentation
    runs-on: ubuntu-latest
    # needs: docs-style
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.DOC_PYTHON_VERSION }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools tox
      - name: Generate the documentation with tox
        run: tox -e doc